#! /usr/bin/env zsh

source $MY/core/helper

echo_space
echo_title_install "brew packages @ $OS_PROFILE"

brewinstall mariadb@10.1
brewinstall elasticsearch@2.4
brewinstall redis

echo_space
echo_title_install "apps @ $OS_PROFILE"

caskinstall google-chrome
caskinstall google-chrome-canary
caskinstall firefox
caskinstall zeplin
caskinstall figma
caskinstall ngrok
