#! /usr/bin/env zsh

source $MY/core/helper

echo_title_update "work macosx settings"

###############################################################################
# General UI/UX                                                               #
###############################################################################

sudo scutil --set ComputerName "_kud.work"
sudo scutil --set HostName "_kud.work"
sudo scutil --set LocalHostName "kud-work"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "kud-work"
