#! /usr/bin/env zsh

source $MY/core/helper

echo_title_install "PHP"

brewinstall php56 --with-imap --disable-opcache --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --without-apache --without-fpm
brewinstall php56-mcrypt
brewinstall php56-geoip
brewinstall php56-igbinary
# brewinstall php56-msgpack
brewinstall php56-memcached --with-igbinary
brewinstall php56-redis --with-igbinary
brewinstall php56-twig
brewinstall php56-yaml
brewinstall php56-xdebug

composer self-update --clean-backups
