#! /usr/bin/env zsh

source $MY/core/helper

echo_space
echo_title_install "brew packages @ work"

brewinstall php56 --disable-opcache --with-debug --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl --without-snmp
brewinstall php56-igbinary
brewinstall php56-xdebug
brewinstall php56-mcrypt
brewinstall php56-memcached --with-igbinary
brewinstall php56-redis --with-igbinary

echo_space
echo_title_install "apps @ work"

caskinstall virtualbox
# caskinstall vagrant

caskinstall google-chrome
caskinstall google-chrome-canary

caskinstall firefox
caskinstall firefox-nightly
