#! /usr/bin/env zsh

source $MY/core/helper

echo_space
echo_title_install "brew packages @ work"

brewinstall php55 --with-debug --with-homebrew-curl --with-homebrew-libxslt --with-homebrew-openssl
brewinstall php55-memcached
brewinstall php55-mcrypt

echo_space
echo_title_install "apps @ work"

caskinstall virtualbox
caskinstall vagrant

caskinstall google-chrome
caskinstall google-chrome-beta
caskinstall google-chrome-dev

caskinstall firefox
caskinstall firefox-aurora
