#! /usr/bin/env zsh

source $MY/core/helper

# echo_space
# echo_title_install "brew packages @ $OS_PROFILE"

echo_space
echo_title_install "apps @ $OS_PROFILE"

caskinstall deluge
caskinstall steam
caskinstall molotov
caskinstall rawtherapee
caskinstall darktable
caskinstall signal
