#! /usr/bin/env zsh

source $MY/core/helper

# echo_space
# echo_title_install "brew packages @ $OS_PROFILE"

echo_space
echo_title_install "apps @ $OS_PROFILE"

caskinstall gswitch
caskinstall darktable
caskinstall deluge
caskinstall rawtherapee
caskinstall signal
caskinstall steam
caskinstall shadow
caskinstall steermouse # http://plentycom.jp/en/steermouse/
