#! /usr/bin/env zsh

source $MY/core/helper

echo_space
echo_title_update "macosx settings @ $OS_PROFILE"

###############################################################################
# General UI/UX                                                               #
###############################################################################

sudo scutil --set ComputerName "_kud.home"
sudo scutil --set HostName "_kud.home"
sudo scutil --set LocalHostName "kud-home"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "kud-home"

# Disable to boot when open the lib
sudo nvram AutoBoot=%00
# sudo nvram AutoBoot=%03
