#! /usr/bin/env zsh

# > Why this patch?
# Alfred is not needed anymore since Yosemite gives us a good launcher.

source $MY/core/helper

echo_title "Removing alfred..."

brew cask uninstall alfred

echo_space
echo_success "Alfred removed!"
