################################################################################
#                                                                              #
#   🚀 ABBREVIATIONS CONFIGURATION                                             #
#   -------------------------------                                            #
#   Shell abbreviations for common commands                                    #
#                                                                              #
################################################################################

abbreviations:
  gcm: "git commit -m"
  ghrc: 'gh repo create "${PWD##*/}" --source=. --push'
  glv: "git lazy-version"
  gmg: "git merge"
  gp: "git push"
  gpo: "git push origin"
  gscr: "git switch -c"
  ocr: "opencode run"
