################################################################################
#                                                                              #
#   🚀 ABBREVIATIONS CONFIGURATION                                             #
#   -------------------------------                                            #
#   Shell abbreviations for common commands                                    #
#                                                                              #
################################################################################

abbreviations:
  # Navigation
  "~": "cd ~"

  # Git shortcuts
  gaa: "git add --all"
  gbr: "git branch"
  gcm: "git commit -m"
  gco: "git checkout"
  gl: "git pull"
  glv: "git lazy-version"
  gmg: "git merge"
  gp: "git push"
  gpo: "git push origin"
  gsc: "git switch -c"
  gst: "git status"
