# Claude Code Configuration - Common
# Settings applied to all profiles

# General settings (keys must match .claude.json keys exactly)
settings:
  autoUpdates: true
  theme: dark-daltonized

# Common MCP servers (all profiles)
mcp:
  github:
    transport: http
    url: https://api.githubcopilot.com/mcp/
  notion:
    transport: http
    url: https://mcp.notion.com/mcp
  figma-remote-mcp:
    transport: http
    url: https://mcp.figma.com/mcp
