#! /usr/bin/env zsh

source $MY/core/helper

aicommits config set type=conventional
aicommits config set max-length=100
aicommits config set model=gpt-4o-mini

oco config set OCO_PROMPT_MODULE=conventional-commit
oco config set OCO_EMOJI=true
oco config set OCO_MODEL=gpt-4o-mini
