#! /usr/bin/env zsh
source $MY/core/helper

# warn about apps coming from app store
echo_space
echo_title "Don't forget to install via App Store"

# if [ ! -d "/Applications/Twitter.app/" ]; then
#   echo "- Twitter for Mac"
# fi
if [ ! -d "/Applications/Tweetbot.app/" ]; then
  echo "- Tweetbot"
fi
if [ ! -d "/Applications/Xcode.app/" ]; then
  echo "- XCode"
fi
echo "- Network Link Conditioner"
if [ ! -d "/Applications/Xscope.app/" ]; then
  echo "- Xscope"
fi
