#! /usr/bin/env zsh
if [ ! -d "$HOME/my/" ]; then
  git clone https://github.com/kud/my.git ~/my &&
fi
source $MY/core/intro
echo_space
~/my/core/dotfiles &&
~/my/core/applescripts &&
~/my/core/rocknroll &&
~/my/core/osx

exec $SHELL
