#! /usr/bin/env zsh
if [ ! -d "$HOME/my/" ]; then
  git clone https://github.com/kud/my.git ~/my &&
fi
export MY=$HOME/my
source $MY/core/intro
echo_space
$MY/core/dotfiles &&
#$MY/core/applescripts &&
$MY/core/rocknroll &&
$MY/core/osx

echo "Do not forget to set up:"
echo ""
echo "- Firefox settings (`£ firefox-settings` + `Customize`)"
echo "- Tweetbot (everything)"
echo "- Dock (move it)"
echo "- SSH for GitHub (https://help.github.com/articles/connecting-to-github-with-ssh/)"

exec $SHELL
