#! /usr/bin/env zsh

source $MY/core/helper

## define cask application folder
export HOMEBREW_CASK_OPTS=--appdir=/Applications

## install brew if needed
if ! type "brew" > /dev/null; then
  echo_space
  echo_title_install "homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

## install zsh via brew if needed
if ! type "/usr/local/bin/zsh" > /dev/null; then
  echo_space
  echo_title_install "zsh"
  brewinstall zsh
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/zsh $USER
  # sudo mv /etc/{zshenv,zprofile}
fi

## install bash via brew if needed
if ! type "/usr/local/bin/bash" > /dev/null; then
  echo_space
  echo_title_install "bash"
  brewinstall bash
  echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
fi

## update/upgrade brew
echo_space
echo_title_update "brew"
brew update && brew upgrade && brew cask upgrade

## install brew packages
echo_space
echo_title_install "brew packages"

### tap
brewtap homebrew/cask
brewtap homebrew/cask-fonts
brewtap homebrew/cask-versions
brewtap elastic/tap
brewtap federico-terzi/espanso

### system
brewinstall ssh-copy-id
brewinstall make
brewinstall archey # system information
brewinstall mitmproxy
brewinstall pv
brewinstall md5sha1sum
brewinstall tree
brewinstall ncdu
brewinstall htop
brewinstall iftop
brewinstall pwgen
brewinstall exiftool
brewinstall grep
brewinstall pcre2
brewinstall htmlcompressor
brewinstall mozjpeg
brewinstall gifsicle
brewinstall ffmpeg
brewinstall rename
brewinstall neurobin/pkg/rnm
brewinstall exa # Modern replacement for 'ls' — https://the.exa.website
brewinstall less # because the macOS built-in version is old
brewinstall p7zip
brewinstall autojump
brewinstall brightness
brewinstall z
brewinstall ripgrep
brewinstall gnu-sed
# brewinstall ffmpeg --with-libass --with-fontconfig
# brewinstall terminal-notifier

### network
brewinstall rsync
brewinstall wget
brewinstall curl
brewinstall lsof
brewinstall tcpflow # analyse tcp requests
brewinstall mtr
brewinstall dnsmasq

### git
brewinstall git
brewinstall ghi
brewinstall tig
brewinstall hub
brewinstall lazygit

### editors
brewinstall vim

### languages
brewinstall zlib # needed for python
brewinstall readline # needed for python
brewinstall xz # needed for python

brewinstall java
sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
brewinstall ruby
brewinstall python # however, will be installed via pyenv after
brewinstall python3 # however, will be installed via pyenv after
brewinstall pyenv
brewinstall pyenv-virtualenv
brewinstall node
brewinstall yarn
brewinstall jesseduffield/lazynpm/lazynpm

### sync/backup
brewinstall syncthing

### others
brewinstall heroku/brew/heroku
brewinstall elastic/tap/elasticsearch-full
brewinstall elastic/tap/kibana-full
brewinstall youtube-dl
brewinstall pdf-redact-tools
brewinstall imagemagick
brewinstall mas # Mac App Store command line interface - https://github.com/mas-cli/mas
brewinstall bat # https://github.com/sharkdp/bat
brewinstall httpie
brewinstall jq
brewinstall ipcalc
brewinstall asciinema
brewinstall openssl@1.1
brewinstall glow
brewinstall loom
brewinstall espanso
# brewinstall pdftk
# brewinstall imagemagick --with-fontconfig

echo_space
echo_title "Cleaning brew..."
brew cleanup

## install apps
echo_space
echo_title_install "apps"

# caskinstall dropbox
# if [ ! -d "$HOME/Dropbox" ]; then
#   read \?"Configure now your dropbox and press [Enter] when you've finished..."
# fi

caskinstall sync
if [ ! -d "$HOME/Sync" ]; then
  read \?"Configure now your sync and press [Enter] when you've finished..."
fi

caskinstall flux
# caskinstall iterm2
caskinstall iterm2-nightly
# caskinstall iterm2-beta
caskinstall appcleaner
caskinstall macpass
caskinstall rectangle
caskinstall grandperspective
caskinstall cloudup
caskinstall xquartz
caskinstall flash-player
caskinstall prefs-editor
caskinstall android-file-transfer
caskinstall kap
caskinstall etrecheckpro
caskinstall monodraw
caskinstall github-beta
caskinstall gitkraken
caskinstall gitup
caskinstall xrg
caskinstall molotov
caskinstall insomnia # REST Client — https://insomnia.rest/
# caskinstall sublime-text-dev
# if ! type "subl" > /dev/null; then
#   ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
# fi
caskinstall sublime-merge-dev
caskinstall firefox-nightly
# caskinstall atom
caskinstall discord
caskinstall deluge
caskinstall imagealpha
caskinstall imageoptim
caskinstall spotify
caskinstall steam
# caskinstall kodi
caskinstall vlc
caskinstall slack
caskinstall image2icon
caskinstall rocket
caskinstall macmediakeyforwarder
caskinstall mark-text # https://marktext.github.io/website/
caskinstall steermouse # http://plentycom.jp/en/steermouse/
# caskinstall background-music
caskinstall background-music-pre
caskinstall fliqlo
caskinstall tyke
caskinstall sip
# caskinstall alfred
caskinstall raycast
caskinstall rawtherapee
caskinstall darktable
caskinstall visual-studio-code
# caskinstall typora
caskinstall proxyman
caskinstall adoptopenjdk
# caskinstall zettlr
caskinstall removebg
caskinstall openmtp
caskinstall altair-graphql-client
caskinstall duf
# caskinstall flashlight
# caskinstall mysimbl
# caskinstall vlc-nightly
# caskinstall beardedspice # http://beardedspice.github.io/
# caskinstall gfxcardstatus # https://gfx.io/
# caskinstall monitorcontrol
# caskinstall nativedisplaybrightness
# caskinstall cheatsheet

# quicklook plugins
caskinstall qlcolorcode
caskinstall qlstephen
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall qlimagesize
caskinstall suspicious-package
caskinstall quicklookase
caskinstall qlvideo
caskinstall qlprettypatch
xattr -d -r com.apple.quarantine ~/Library/QuickLook # remove quarantine attr since Catalina

source $MY/profiles/$OS_PROFILE/core/brew 2> /dev/null

echo_space
echo_title "Cleaning brew cask..."
brew cleanup

