#! /usr/bin/env zsh

source $MY/core/helper

## define cask application folder
export HOMEBREW_CASK_OPTS=--appdir=/Applications

## install brew
if ! type "brew" > /dev/null; then
  echo_space
  echo_title_install "homebrew"
  sudo -v
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

## install zsh
if [[ $(which zsh) == "/bin/zsh" ]]; then
  echo_space
  echo_title_install "zsh"
  brewinstall zsh
  echo "${HOMEBREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells
  chsh -s ${HOMEBREW_PREFIX}/bin/zsh
fi

## install bash
if [[ $(which bash) == "/bin/bash" ]]; then
  echo_space
  echo_title_install "bash"
  brewinstall bash
  echo "${HOMEBREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells
fi

## update/upgrade brew
echo_space
echo_title_update "brew"
brew update && brew upgrade

## install brew packages
echo_space
echo_title_install "brew packages"

### tap
brewtap homebrew/cask
brewtap homebrew/cask-fonts
brewtap homebrew/cask-versions

### system
brewinstall ssh-copy-id
brewinstall make
brewinstall neofetch # system information
brewinstall mitmproxy
brewinstall pv
brewinstall fd
brewinstall md5sha1sum
brewinstall tree
brewinstall ncdu
brewinstall htop
brewinstall iftop
brewinstall pwgen
brewinstall exiftool
brewinstall grep
brewinstall pcre2
brewinstall htmlcompressor
brewinstall mozjpeg
brewinstall gifsicle
brewinstall ffmpeg
brewinstall rename
brewinstall neurobin/pkg/rnm
brewinstall exa # Modern replacement for 'ls' — https://the.exa.website
brewinstall less # because the macOS built-in version is old
brewinstall p7zip
brewinstall autojump
brewinstall brightness
brewinstall z
brewinstall ripgrep
brewinstall gnu-sed

### network
brewinstall rsync
brewinstall rclone
brewinstall wget
brewinstall curl
brewinstall lsof
brewinstall tcpflow # analyse tcp requests
brewinstall mtr
brewinstall dnsmasq
brewinstall syncthing

### git
brewinstall git
brewinstall gh
# brewinstall ghi
brewinstall tig
brewinstall hub
brewinstall lazygit

### editors
brewinstall vim

### languages
brewinstall zlib # needed for python
brewinstall readline # needed for python
brewinstall xz # needed for python

brewinstall java
sudo ln -sfn ${HOMEBREW_PREFIX}/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
brewinstall ruby
brewinstall python # however, will be installed via pyenv after
brewinstall pyenv
brewinstall pyenv-virtualenv
brewinstall node # @TODO: could be an idea to have a manager
brewinstall yarn
brewinstall jesseduffield/lazynpm/lazynpm

### others
brewinstall heroku/brew/heroku
brewinstall yt-dlp
brewinstall imagemagick
brewinstall mas # Mac App Store command line interface - https://github.com/mas-cli/mas
brewinstall bat # https://github.com/sharkdp/bat
brewinstall httpie
brewinstall jq
brewinstall ipcalc
brewinstall asciinema
brewinstall openssl
brewinstall glow
brewinstall loom
brewinstall svn # for Ubuntu fonts

## install apps
echo_space
echo_title_install "apps"

if [ ! -d "$HOME/pCloud" ]; then
  read "?Install and configure pCloud and press [Enter] when you've finished..."
fi

caskinstall flux
# caskinstall iterm2
# caskinstall iterm2-beta
caskinstall iterm2-nightly
caskinstall appcleaner
caskinstall rectangle
caskinstall grandperspective
caskinstall xquartz
caskinstall flash-player
caskinstall prefs-editor
caskinstall android-file-transfer
# caskinstall kap
caskinstall etrecheckpro
caskinstall monodraw
# caskinstall github-beta
# caskinstall gitkraken
caskinstall gitup
caskinstall xrg
caskinstall insomnia # REST Client — https://insomnia.rest/
# caskinstall sublime-text-dev
# if ! type "subl" > /dev/null; then
#   ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ${HOMEBREW_PREFIX}/bin/subl
# fi
caskinstall sublime-merge-dev
caskinstall firefox-nightly
caskinstall discord
caskinstall imagealpha
caskinstall imageoptim
caskinstall spotify
# caskinstall kodi
caskinstall vlc
caskinstall slack
caskinstall image2icon
caskinstall rocket
caskinstall macmediakeyforwarder
caskinstall mark-text # https://marktext.github.io/website/
caskinstall steermouse # http://plentycom.jp/en/steermouse/
# caskinstall background-music
caskinstall background-music-pre
caskinstall fliqlo
caskinstall tyke
caskinstall sip
caskinstall raycast
caskinstall visual-studio-code
# caskinstall typora
caskinstall proxyman
caskinstall adoptopenjdk
# caskinstall zettlr
caskinstall removebg
caskinstall openmtp
caskinstall altair-graphql-client
caskinstall duf
caskinstall xcodes
caskinstall keepassxc
caskinstall cleanshot
caskinstall pixelsnap
# caskinstall flashlight
# caskinstall mysimbl
# caskinstall vlc-nightly
# caskinstall beardedspice # http://beardedspice.github.io/
# caskinstall gfxcardstatus # https://gfx.io/
# caskinstall monitorcontrol
# caskinstall nativedisplaybrightness
# caskinstall cheatsheet

# quicklook plugins
caskinstall qlcolorcode
caskinstall qlstephen
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall qlimagesize
caskinstall suspicious-package
caskinstall quicklookase
caskinstall qlvideo
caskinstall qlprettypatch
xattr -d -r com.apple.quarantine ~/Library/QuickLook # remove quarantine attr since Catalina

source $MY/profiles/$OS_PROFILE/core/brew 2> /dev/null

echo_space
echo_title "Cleaning brew cask..."
brew cleanup

echo_space
echo_title "Doctor is checking..."
brew doctor


