#! /usr/bin/env zsh
source $MY/core/helper

# install apps
echo_space
echo_title_install "apps"

# caskinstall dropbox
# if [ ! -d "$HOME/Dropbox" ]; then
#   read \?"Configure now your dropbox and press [Enter] when you've finished..."
# fi

caskinstall sync
if [ ! -d "$HOME/Sync" ]; then
  read \?"Configure now your sync and press [Enter] when you've finished..."
fi

caskinstall java # sorry my love :(
# caskinstall alfred
caskinstall flux
caskinstall iterm2
caskinstall appcleaner
caskinstall keepassx
caskinstall spectacle
caskinstall gifrocket
caskinstall grandperspective
caskinstall cloudup
caskinstall xquartz
caskinstall flash
caskinstall bittorrent-sync
caskinstall qlcolorcode
caskinstall qlstephen
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall prefs-editor
caskinstall qlprettypatch
caskinstall betterzipql
caskinstall webp-quicklook
caskinstall suspicious-package
caskinstall ios7-screensaver
caskinstall android-file-transfer
caskinstall licecap
caskinstall etrecheck
caskinstall macdown
caskinstall monodraw
# caskinstall recordit
# caskinstall xscope
# caskinstall google-drive

caskinstall font-ubuntu
caskinstall font-ubuntu-mono-powerline

# caskinstall sublime-text3
caskinstall sublime-text-dev
if ! type "subl" > /dev/null; then
  ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
fi
caskinstall firefox-nightly
# caskinstall firefoxdeveloperedition

caskinstall limechat

caskinstall imagealpha
caskinstall imageoptim
caskinstall img2icns

caskinstall spotify
caskinstall vlc

echo_space
echo_title "Cleaning brew cask..."
brew cask cleanup
