#!/usr/bin/env zsh

source "$MY/core/helper"

echo_title_install "dotfiles"

dotfiles=(
  ".aliases"
  ".config/nvim/init.vim"
  ".editorconfig"
  ".gemrc"
  ".gitattributes"
  ".gitconfig"
  ".gitignore_global"
  ".p10k.zsh"
  ".prettierrc"
  ".vimrc"
  ".zpreztorc"
  ".zshrc"
)

for file in "${dotfiles[@]}"; do
  ln -sf "$MY/dotfiles/$file" "${ZDOTDIR:-$HOME}/$file" 2>/dev/null
done

if [ ! -f "$HOME/.ssh/config" ]; then
  cp "$MY/templates/ssh/config" "$HOME/.ssh/"
fi

# local files
if [ ! -f "$HOME/.zshrc_local" ]; then
  echo "export OS_PROFILE=DEFINE_ME" >"$HOME/.zshrc_local"

  read "?Configure now your 'OS_PROFILE' in '~/.zshrc_local' and press [Enter] when you've finished..." </dev/tty
fi

if [ ! -f "$HOME/.gitconfig_local" ]; then
  echo "[github]
  user = USERNAME
[user]
  name = FIRSTNAME LASTNAME
  email = EMAIL
[includeIf \"gitdir:~/Projects/work/\"]
  path = .gitconfig_local_work" >"$HOME/.gitconfig_local"

  read "?Configure now your git informations in '~/.gitconfig_local' and press [Enter] when you've finished..." </dev/tty
fi

# reload the shell
source "$HOME/.zshrc"

echo_success "Dotfiles are installed!"
