#!/usr/bin/env zsh

# Load helper functions
source $MY/core/helper

# Determine Firefox profile path
PROFILE_DIR="$HOME/Library/Application Support/Firefox/Profiles"
DEFAULT_FOLDER=$(ls "$PROFILE_DIR" | grep .default-nightly)
PREFS_FILE="$PROFILE_DIR/$DEFAULT_FOLDER/prefs.js"
CONTAINERS_FILE="$PROFILE_DIR/$DEFAULT_FOLDER/containers.json"

# Close Firefox Nightly to safely apply changes
quit "Firefox Nightly"
sleep 5

echo_title_update "Applying Firefox settings"

# Function to update Firefox preferences
update_pref() {
  local key="$1"
  local value="$2"
  echo "user_pref(\"$key\", $value);" >>"$PREFS_FILE"
}

# ╔═════════════════════════════════════════════╗
# ║                Global Preferences           ║
# ╚═════════════════════════════════════════════╝

# Disable warning on about:config
update_pref "browser.aboutConfig.showWarning" false

# Disable zoom with Cmd + Mousewheel
update_pref "mousewheel.with_meta.action" 0

# Turn off domain guessing
update_pref "browser.fixup.alternate.enabled" false

# Disable warning when closing tabs
update_pref "browser.tabs.warnOnClose" false

# Disable web search in the address bar
update_pref "keyword.enabled" false

# Enable punycode to prevent phishing
update_pref "network.IDN_show_punycode" true

# Disable Pocket
update_pref "extensions.pocket.enabled" false

# Disable search suggestions
update_pref "browser.search.suggest.enabled" false

# Hide specific search engines
update_pref "browser.search.hiddenOneOffs" '"Google,Bing,Amazon.co.uk,Chambers (UK),DuckDuckGo,eBay,Twitter,Wikipedia (en)"'

# Prevent closing the window when the last tab is closed
update_pref "browser.tabs.closeWindowWithLastTab" false

# Allow "resend" network queries
update_pref "browser.opaqueResponseBlocking.javascriptValidator" false

# Enable auto-hide in fullscreen mode
update_pref "browser.fullscreen.autohide" true

# Disable Safari-like modal highlights for Find
update_pref "findbar.modalHighlight" false

# Disable the megabar for URL search
update_pref "browser.urlbar.megabar" false

# Enable query stripping for privacy
update_pref "privacy.query_stripping.enabled" true

# Disable auto-scroll on middle click
update_pref "general.autoScroll" false

# Enable Picture-in-Picture (PiP) when switching tabs
update_pref "media.videocontrols.picture-in-picture.enable-when-switching-tabs.enabled" true

# Enable AI chat feature
update_pref "browser.ml.chat.enabled" true

# Set the AI chat provider
update_pref "browser.ml.chat.provider" '"https://chatgpt.com"'

# Enable sidebar revamp
update_pref "sidebar.revamp" true

# Enable vertical tabs in the sidebar
update_pref "sidebar.verticalTabs" true

# ╔═════════════════════════════════════════════╗
# ║                Sync Preferences             ║
# ╚═════════════════════════════════════════════╝

# Ignore addon enable/disable during sync
update_pref "services.sync.prefs.sync.addons.ignoreUserEnabledChanges" true

# Decline syncing form data and history
update_pref "services.sync.declinedEngines" '"forms,history"'

# ╔═════════════════════════════════════════════╗
# ║             Developer Tools Settings        ║
# ╚═════════════════════════════════════════════╝

# Enable browser chrome debugging
update_pref "devtools.chrome.enabled" true

# Enable eyedropper tool
update_pref "devtools.command-button-eyedropper.enabled" true

# Enable paint flashing tool
update_pref "devtools.command-button-paintflashing.enabled" true

# Disable responsive design mode
update_pref "devtools.command-button-responsive.enabled" false

# Enable Scratchpad tool
update_pref "devtools.command-button-scratchpad.enabled" true

# Enable screenshot tool
update_pref "devtools.command-button-screenshot.enabled" true

# Disable split console
update_pref "devtools.command-button-splitconsole.enabled" false

# Enable remote debugging
update_pref "devtools.debugger.remote-enabled" true

# Enable DOM inspection
update_pref "devtools.dom.enabled" true

# Set editor keymap to Sublime Text
update_pref "devtools.editor.keymap" '"sublime"'

# Log telemetry onboarding
update_pref "devtools.onboarding.telemetry.logged" true

# Enable new performance panel
update_pref "devtools.performance.new-panel-enabled" true

# Enable Scratchpad tool
update_pref "devtools.scratchpad.enabled" true

# Disable audio in screenshots
update_pref "devtools.screenshot.audio.enabled" false

# Set DevTools to open in a side pane
update_pref "devtools.toolbox.host" '"side"'

# Enable timestamps in console messages
update_pref "devtools.webconsole.timestampMessages" true

# Enable WebIDE widget
update_pref "devtools.webide.widget.enabled" true

# Disable cache during development
update_pref "devtools.cache.disabled" true

# Enable local tab debugging
update_pref "devtools.aboutdebugging.local-tab-debugging" true

source $MY/profiles/$OS_PROFILE/core/firefox-settings 2>/dev/null

echo_success "Firefox settings have been applied."

# ╔═════════════════════════════════════════════╗
# ║               Containers                    ║
# ╚═════════════════════════════════════════════╝

cat <<EOF >"$CONTAINERS_FILE"
{
  "version": 5,
  "lastUserContextId": 322,
  "identities": [
    {
      "icon": "fingerprint",
      "color": "blue",
      "public": true,
      "userContextId": 1,
      "name": "Personal"
    },
    {
      "icon": "briefcase",
      "color": "red",
      "public": true,
      "userContextId": 2,
      "name": "Work"
    },
    {
      "icon": "chill",
      "color": "yellow",
      "public": true,
      "userContextId": 318,
      "name": "Streaming"
    },
    {
      "icon": "fingerprint",
      "color": "turquoise",
      "public": true,
      "userContextId": 649,
      "name": "Personal at Work"
    },
    {
      "icon": "fence",
      "color": "blue",
      "public": true,
      "userContextId": 322,
      "name": "Facebook"
    }
  ]
}
EOF

echo_success "Firefox containers have been synchronised."

sleep 2

open -a "Firefox Nightly"
