#! /usr/bin/env zsh
source $MY/core/helper

echo_title_install "fonts"

cp ${SYNC_FOLDER}/Lib/fonts/Operator\ Mono/* ~/Library/Fonts &>/dev/null
cp ${SYNC_FOLDER}/Lib/fonts/Operator\ Mono\ Lig/* ~/Library/Fonts &>/dev/null

caskinstall font-3270-nerd-font
caskinstall font-arimo-nerd-font
caskinstall font-cascadia-code
caskinstall font-cascadia-mono
caskinstall font-cousine-nerd-font
caskinstall font-fira-code
caskinstall font-go-mono-nerd-font
caskinstall font-hack-nerd-font
caskinstall font-hubot-sans
caskinstall font-inconsolata-nerd-font
caskinstall font-iosevka-nerd-font
caskinstall font-jetbrains-mono
caskinstall font-jetbrains-mono-nerd-font
caskinstall font-lekton-nerd-font
caskinstall font-mona-sans
caskinstall font-monofur-nerd-font
caskinstall font-monoid-nerd-font
caskinstall font-mononoki-nerd-font
caskinstall font-noto-nerd-font
caskinstall font-profont-nerd-font
caskinstall font-tinos-nerd-font
caskinstall font-ubuntu
caskinstall font-ubuntu-mono-derivative-powerline
caskinstall font-ubuntu-nerd-font
caskinstall font-symbols-only-nerd-font

echo_success "Fonts are done!"
