#! /usr/bin/env zsh

# set colours
autoload colors
if [[ "$terminfo[colors]" -gt 8 ]]; then
  colors
fi

for COLOUR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
  eval COLOUR_$COLOUR='$fg_no_bold[${(L)COLOUR}]'
  eval COLOUR_BOLD_$COLOUR='$fg_bold[${(L)COLOUR}]'
done
eval COLOUR_RESET='$reset_color'

export CHAR_OK=✔
export CHAR_ERROR=✗
export CHAR_STARTER=❯

function echo_info () { echo "${COLOUR_BLUE}[i]${COLOUR_RESET} $1" }
function echo_user () { echo "${COLOUR_YELLOW}[?]${COLOUR_RESET} $1" }
function echo_success () { echo "${COLOUR_GREEN}${CHAR_OK}${COLOUR_RESET} $1" }
function echo_fail () { echo "${COLOUR_RED}${CHAR_ERROR}${COLOUR_RESET} $1|n"; exit }
function echo_title () { echo "${COLOUR_CYAN}${CHAR_STARTER} $@${COLOUR_RESET}" }
function echo_title_install () { echo_title "Installing" $1"..." }
function echo_title_update () { echo_title "Updating" $1"..." }
function echo_space () { printf "\n" }
function echo_spacex2 () {
  echo_space
  echo_space
}
function echo_spacex3 () {
  echo_space
  echo_space
  echo_space
}

# easy brew install function
function brewinstall() {
  # brew install "${@}" 2> /dev/null
  brew install "${@}"
  brew upgrade "${@}"
}

function brewuninstall() {
  brew uninstall "${@}"
}

# easy cask install function
function caskinstall() {
  # brew cask install "${@}" 2> /dev/null
  brew install --cask "${@}"
}

function caskuninstall() {
  brew uninstall --cask "${@}"
}

# easy ruby package install function
function geminstall() {
  if ! type "${@}" > /dev/null; then
    gem install "${@}"
  fi
}

# easy global node package install function
function npminstall() {
  if ! type "${@}" > /dev/null; then
    npm install "${@}" -g --quiet
  fi
}

# easy global python package install function
function pipi2nstall() {
  if ! type "${@}" > /dev/null; then
    pip2 install --upgrade "${@}"
  fi
}

function pip3install() {
  if ! type "${@}" > /dev/null; then
    pip3 install --upgrade "${@}"
  fi
}

# easy brew tap function
function brewtap() {
  if ! brew tap | grep "${@}" > /dev/null; then
    brew tap "${@}"
  fi
}
