#! /usr/bin/env zsh

open https://apps.apple.com/us/app/xcode/id497799835

echo "Please install Xcode from the App Store, then press Enter here to continue."
read pause

echo "Confirming agreement with Xcode license..."
sudo xcodebuild -license accept

echo "Installing Xcode command line tools..."
xcode-select --install

echo "Setting Xcode developer directory..."
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

echo "Running Xcode first launch..."
xcodebuild -runFirstLaunch

echo "and now the magic 💫..."

if [ ! -d "$HOME/my/" ]; then
  git clone https://github.com/kud/my.git ~/my &&
fi

export MY=$HOME/my

$MY/core/intro &&
$MY/core/default-folders &&
$MY/core/dotfiles &&
$MY/core/main &&
$MY/core/symlink &&
$MY/core/fonts &&
$MY/core/os &&

open https://github.com/kud/my/blob/master/doc/postinstall.md

exec $SHELL

$MY/core/doctor
