#! /usr/bin/env zsh

open https://apps.apple.com/us/app/xcode/id497799835

echo "Please install Xcode from the App Store, then press Enter here to continue."
read pause

echo "Confirming agreement with Xcode license..."
sudo xcodebuild -license accept

echo "Installing Xcode command line tools..."
xcode-select --install

echo "Setting Xcode developer directory..."
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

echo "Running Xcode first launch..."
xcodebuild -runFirstLaunch

echo "and now the magic 💫..."

PROJECT_DIR="$HOME/my"
GIT_REPO="git@github.com:kud/my.git"

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo "Cloning repository..."
    git clone "$GIT_REPO" "$PROJECT_DIR"
fi

if [[ -d "$PROJECT_DIR" ]]; then
    echo "Updating remote URL to SSH..."
    git -C "$PROJECT_DIR" remote set-url origin "$GIT_REPO"
fi

export MY=$HOME/my

$MY/core/intro &&
$MY/core/default-folders &&
$MY/core/dotfiles &&
$MY/core/main &&
$MY/core/ssh &&
$MY/core/symlink &&
$MY/core/os &&

open https://github.com/kud/my/blob/master/doc/postinstall.md

exec $SHELL

$MY/core/doctor
