#! /usr/bin/env zsh

if [ ! -d "$HOME/my/" ]; then
  git clone https://github.com/kud/my.git ~/my &&
fi

export MY=$HOME/my

$MY/core/intro &&
$MY/core/default-folders &&
$MY/core/dotfiles &&
$MY/core/main &&
$MY/core/symlink &&
$MY/core/fonts &&
# $MY/core/os &&

open https://github.com/kud/my/blob/master/doc/postinstall.md

exec $SHELL
