#! /usr/bin/env zsh
setopt EXTENDED_GLOB

source $MY/core/helper

$MY/core/pcloud
$MY/core/prezto
$MY/core/brew
$MY/core/antidote
$MY/core/submodules
$MY/core/neovim
$MY/core/gem
$MY/core/pip
$MY/core/npm
$MY/core/mas
$MY/core/aicommits
$MY/core/sublime-merge
$MY/core/keepassxc
