#! /usr/bin/env zsh
source $MY/core/helper

echo_space
echo_title_install "apps from AppStore"

# if [ ! -d "/Applications/Xcode.app/" ]; then
#  mas install 497799835
# else
#  xcode-select --install
# fi

if [ ! -d "/Applications/Tweetbot.app/" ]; then
  mas install 1384080005
fi

if [ ! -d "/Applications/xScope.app/" ]; then
  mas install 889428659
fi

if [ ! -d "/Applications/GIF Brewery 3.app/" ]; then
  mas install 1081413713
fi

source $MY/profiles/$OS_PROFILE/core/mas 2> /dev/null

echo_space
echo_title_update "apps from AppStore"

mas upgrade
