#! /usr/bin/env zsh
source $MY/core/helper

echo_space
echo_title_install "apps from AppStore"

# if [ ! -d "/Applications/Xcode.app/" ]; then
#  mas install 497799835
# else
#  xcode-select --install
# fi

source $MY/profiles/$OS_PROFILE/core/mas 2> /dev/null

echo_space
echo_title_update "apps from AppStore"

mas upgrade
