#! /usr/bin/env zsh
source $MY/core/helper

echo_space
echo_title_install "apps from AppStore"

# if [ ! -d "/Applications/Xcode.app/" ]; then
#  mas install 497799835
# else
#  xcode-select --install
# fi

mas install 1384080005 # Tweetbot 3
mas install 889428659 # xScope
mas install 1081413713 # GIF Brewery 3

source $MY/profiles/$OS_PROFILE/core/mas 2> /dev/null

echo_space
echo_title_update "apps from AppStore"

mas upgrade
