#! /usr/bin/env zsh
source $MY/core/helper

# install npm
# if ! type "npm" > /dev/null; then
#   echo_space
#   echo_title_install "npm"
#   curl -sL https://npmjs.org/install.sh | sh
# fi

echo_space
echo_title_update "npm"
npm install -g npm@latest

# update node packages
echo_space
echo_title_update "global node packages"
npm update -g --quiet

# install node packages
echo_space
echo_title_install "global node packages"

npminstall tldr
npminstall nodemon
npminstall jake
npminstall vtop
npminstall http-server
npminstall hicat # command-line syntax highlighter
npminstall figlet-cli
npminstall tmi # too many images
npminstall trash-cli
npminstall svgo
npminstall fraktur # write with great font
npminstall weinre # debugger for web pages — http://people.apache.org/~pmuellr/weinre-docs/latest/
npminstall pageres-cli # responsive website screenshots — https://github.com/sindresorhus/pageres
npminstall npm-check-updates # check if npm modules are updated
npminstall react-native-cli
npminstall gulp-cli
npminstall markdown-live
npminstall caniuse-cmd
npminstall imagemin
npminstall speed-test
npminstall up # cloudup
npminstall uncss # remove useless css
npminstall how2 # stackoverflow from the terminal
npminstall iterm2-tab-set # set iTerm2 tab color, title, and/or badge
# npminstall toggl
# npminstall pure-prompt

# config
npm config set save-exact true
npm config set tag-version-prefix ""
npm config set progress false
