#! /usr/bin/env zsh

# Ask for the administrator password upfront
sudo -v

###############################################################################
# General System Preferences                                                  #
###############################################################################

# Disable system sounds
defaults write NSGlobalDomain com.apple.sound.beep.volume -float 0
defaults write NSGlobalDomain com.apple.sound.uiaudio.enabled -int 0

# Require password immediately after sleep or screen saver begins
defaults -currentHost write com.apple.screensaver idleTime -int 0

# Set language and text formats
defaults write NSGlobalDomain AppleICUNumberSymbols -dict 0 '.' 1 '' 10 '.' 17 ''

# Disable automatic boot when opening the lid
sudo nvram AutoBoot=%00
# To re-enable: sudo nvram AutoBoot=%03

###############################################################################
# Dock                                                                        #
###############################################################################

# Set Dock orientation to bottom
defaults write com.apple.dock orientation -string "bottom"

# Enable App Expose gesture
defaults write com.apple.dock showAppExposeGestureEnabled -int 1

# Disable Desktop gesture
defaults write com.apple.dock showDesktopGestureEnabled -int 0

# Disable Launchpad gesture
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

###############################################################################
# Screen                                                                      #
###############################################################################

# Include date in screenshot filenames
defaults write com.apple.screencapture "include-date" -int 1

# Rename screenshot prefix
defaults write com.apple.screencapture name -string "macos"

###############################################################################
# Finder                                                                      #
###############################################################################

# Hide tags in Finder
defaults write com.apple.finder ShowRecentTags -bool false

# Hide icons on Desktop
defaults write com.apple.finder CreateDesktop -bool false

# Set Finder default view to column view
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

###############################################################################
# Menu Bar & Control Centre                                                   #
###############################################################################

# Example: Enable/disable Control Centre items (uncomment to customise)
# defaults write com.apple.controlcenter "NSStatusItem Visible AirDrop" -int 0
# defaults write com.apple.controlcenter "NSStatusItem Visible Battery" -int 1
# defaults write com.apple.controlcenter "NSStatusItem Visible Bluetooth" -int 1
# defaults write com.apple.controlcenter "NSStatusItem Visible Clock" -int 1
# defaults write com.apple.controlcenter "NSStatusItem Visible Sound" -int 1

###############################################################################
# MiddleClick                                                                 #
###############################################################################

# Configure MiddleClick to use 4 fingers instead of 3
defaults write com.rouge41.middleClick fingers -int 4

###############################################################################
# Miscellaneous Tweaks                                                        #
###############################################################################

# Disable third-party sponsors in JRE Installer
defaults write ~/Library/Application\ Support/JREInstaller/ThirdParty SPONSORS -string "0"

# Disable "recent items" in the Apple menu
defaults write NSGlobalDomain NSRecentDocumentsLimit -int 0
