#! /usr/bin/env zsh

# Ask for the administrator password upfront
sudo -v

# Menu bar
# defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Clock.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" "/System/Library/CoreServices/Menu Extras/Volume.menu" "/System/Library/CoreServices/Menu Extras/Displays.menu"

# Disable sounds
defaults write NSGlobalDomain com.apple.sound.beep.volume -float 0
defaults write NSGlobalDomain com.apple.sound.uiaudio.enabled -int 0

# Require password immediately after sleep or screen saver begins
defaults -currentHost write com.apple.screensaver idleTime -int 0

# Set language and text formats
defaults write NSGlobalDomain AppleICUNumberSymbols -dict 0 '.' 1 '' 10 '.' 17 ''

# Disable to boot when open the lib
sudo nvram AutoBoot=%00
# sudo nvram AutoBoot=%03

# Enable App Expose
defaults write com.apple.dock showAppExposeGestureEnabled -int 1

# Disable showing Desktop
defaults write com.apple.dock showDesktopGestureEnabled -int 0

# Disable showing Launchpad
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

###############################################################################
# Screen                                                                      #
###############################################################################

# Add/Remove date on screenshot name
defaults write com.apple.screencapture "include-date" 1

# Rename screenshot name
defaults write com.apple.screencapture name macos

###############################################################################
# Finder                                                                      #
###############################################################################

# Hide tags
defaults write com.apple.finder ShowRecentTags -bool false

# Hide icons on Desktop
defaults write com.apple.finder CreateDesktop false

# Column view
defaults write com.apple.finder "FXPreferredViewStyle" -string "clmv"

###############################################################################
# Menu Bar & Control Centre                                                   #
###############################################################################

# defaults write com.apple.controlcenter  "NSStatusItem Visible AirDrop" -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible Battery" -int 1
# defaults write com.apple.controlcenter  "NSStatusItem Visible BentoBox" -int 1
# defaults write com.apple.controlcenter  "NSStatusItem Visible Clock" -int 1
# defaults write com.apple.controlcenter  "NSStatusItem Visible KeyboardBrightness" -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible NowPlaying"  -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible Sound" -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible UserSwitcher" -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible WiFi" -int 0
# defaults write com.apple.controlcenter  "NSStatusItem Visible Bluetooth" -int 0

###############################################################################
# Dock                                                                        #
###############################################################################

# Orientation
defaults write com.apple.dock orientation -string "bottom"

###############################################################################
# MiddleClick                                                                 #
###############################################################################

# Use 4 fingers instead of 3
defaults write com.rouge41.middleClick fingers 4

###############################################################################
# Remove shits                                                                #
###############################################################################

defaults write ~/Library/Application\ Support/JREInstaller/ThirdParty SPONSORS -string "0"
