#! /usr/bin/env zsh

source $MY/core/helper

if [ ! -d "$HOME/pCloud" ]; then
  mkdir -p ~/pCloud
  open "https://www.pcloud.com/download-free-online-cloud-file-storage.html"
  read "?Install and configure pCloud and press [Enter] when you've finished..." </dev/tty
fi
