#! /usr/bin/env zsh

source $MY/core/helper

# install python
echo_space
echo_title_update "python"
LATEST_PYTHON_VERSION=$(brew info python|grep '(bottled)'|sed 's/==> python@3...: stable //g'|sed 's/ (bottled).*//g')

pyenv install -s $LATEST_PYTHON_VERSION
pyenv global $LATEST_PYTHON_VERSION

# install python packages
echo_space
echo_title_install "global python packages"

pip3install pip

pip install --upgrade pip
pip-upgrade-all

source $MY/profiles/$OS_PROFILE/core/pip 2> /dev/null
