#! /usr/bin/env zsh
#
source $MY/core/helper

# install python packages
echo_space
echo_title_install "global python packages"

pip3install asciinema

source $MY/profiles/$OS_PROFILE/core/pip 2> /dev/null
