#! /usr/bin/env zsh

source $MY/core/helper

# handle zprezto
if [ -d "$HOME/.zprezto" ]; then
  echo_space
  echo_title_update "prezto"
  cd "$HOME/.zprezto/"
  git pull
  git submodule update --init --recursive
  cd -
else
  echo_space
  echo_title_install "prezto"
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
  echo_space
  echo_title "Copying zprezto files.."
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    cp -ivn "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi
