#! /usr/bin/env zsh
setopt EXTENDED_GLOB

source $MY/core/helper

# define cask application folder
export HOMEBREW_CASK_OPTS=--appdir=/Applications

# easy brew install function
function brewinstall() {
  brew install "${@}" 2> /dev/null
}

# easy cask install function
function caskinstall() {
  brew cask install "${@}" 2> /dev/null
}

# easy ruby package install function
function geminstall() {
  if ! type "${@}" > /dev/null; then
    gem install "${@}"
  fi
}

# easy global node package install function
function npminstall() {
  if ! type "${@}" > /dev/null; then
    npm install "${@}" -g --quiet
  fi
}

# easy global python package install function
function pipinstall() {
  if ! type "${@}" > /dev/null; then
    pip install --upgrade "${@}"
  fi
}

# easy brew tap function
function brewtap() {
  if ! brew tap | grep "${@}" > /dev/null; then
    brew tap "${@}"
  fi
}

# install brew if needed
if ! type "brew" > /dev/null; then
  echo_space
  echo_title_install "homebrew"
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

# install zsh via brew if needed
if ! type "/usr/local/bin/zsh" > /dev/null; then
  echo_space
  echo_title_install "zsh"
  brewinstall zsh
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/zsh $USER
  # sudo mv /etc/{zshenv,zprofile}
fi

# install bash via brew if needed
if ! type "/usr/local/bin/bash" > /dev/null; then
  echo_space
  echo_title_install "bash"
  brewinstall bash
  echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
fi

# update/upgrade brew
echo_space
echo_title_update "brew"
brew update && brew upgrade

# install brew packages
echo_space
echo_title_install "brew packages"

brewtap phinze/cask
brewtap homebrew/dupes
brewtap caskroom/versions
brewtap josegonzalez/php

brewinstall homebrew/dupes/make
brewinstall dnsmasq
brewinstall ssh-copy-id
brewinstall htop-osx
brewinstall homebrew/dupes/rsync

brewinstall git
brewinstall ghi
brewinstall wget
brewinstall curl
brewinstall pv
brewinstall md5sha1sum
brewinstall tree
brewinstall mtr
brewinstall ncdu
brewinstall iftop
brewinstall iotop
brewinstall lsof
brewinstall pwgen
brewinstall mdr
brewinstall vim

brewinstall ruby
brewinstall python
brewinstall node --without-npm
brewinstall php55

brewinstall brew-cask

# install apps
echo_space
echo_title_install "apps"

caskinstall dropbox
if [ ! -d "$HOME/Dropbox" ]; then
  read \?"Configure now your dropbox and press [Enter] when you've finished..."
fi
caskinstall google-chrome-canary
caskinstall firefox-nightly
caskinstall vlc
caskinstall alfred
caskinstall iterm2-beta
caskinstall limechat
caskinstall flux
caskinstall appcleaner
caskinstall keepassx2
caskinstall spectacle
caskinstall grandperspective
caskinstall imagealpha
caskinstall imageoptim
caskinstall steam
caskinstall spotify
caskinstall tinygrab
caskinstall sublime-text3
if ! type "subl" > /dev/null; then
  ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
fi
caskinstall xquartz
caskinstall bittorrent-sync
caskinstall flash
caskinstall qlcolorcode
caskinstall qlstephen
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall qlprettypatch
caskinstall betterzipql
caskinstall webp-quicklook
caskinstall suspicious-package
caskinstall ios7-screensaver
caskinstall recordit
caskinstall xscope

# handle zprezto
if [ -d "$HOME/.zprezto" ]; then
  echo_space
  echo_title_update "prezto"
  git --git-dir="$HOME/.zprezto/.git" --work-tree="$HOME/.zprezto/" pull
else
  echo_space
  echo_title_install "prezto"
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
  echo_space
  echo_title "Copying zprezto files.."
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    cp -ivn "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi

# handle themes
if [ -d "$HOME/my/modules/themes" ]; then
  echo_space
  echo_title_update "themes"
  git --git-dir="$HOME/my/modules/themes/.git" --work-tree="$HOME/my/modules/themes/" pull
else
  echo_space
  echo_title_install "themes"
  git clone --recursive https://github.com/kud/themes.git "$HOME/my/modules/themes"
  mkdir -p ~/Library/Application\ Support/LimeChat/Themes
  ln -si ~/my/modules/themes/limechat/kud.css ~/Library/Application\ Support/LimeChat/Themes/kud.css
  ln -si ~/my/modules/themes/limechat/kud.yaml ~/Library/Application\ Support/LimeChat/Themes/kud.yaml
fi

# vim theme
echo_space
echo_title_update "vim theme"
mkdir -p ~/.vim/colors
rm -f ~/.vim/colors/Tomorrow-Night-Eighties.vim
curl -sL https://raw.github.com/chriskempson/tomorrow-theme/master/vim/colors/Tomorrow-Night-Eighties.vim > ~/.vim/colors/Tomorrow-Night-Eighties.vim

# update ruby packages
echo_space
echo_title_update "gems"
gem update --system && gem update

# install ruby packages
echo_space
echo_title_install "global ruby packages"
geminstall boom

# install ruby packages
echo_space
echo_title_install "global python packages"
pipinstall asciinema

# install npm
if ! type "npm" > /dev/null; then
  echo_space
  echo_title_install "npm"
  curl -sL https://npmjs.org/install.sh | sh
fi

# update node packages
echo_space
echo_title_update "global node modules"
npm update -g --quiet

# install node packages
echo_space
echo_title_install "global packages"
npminstall bower
npminstall tldr
npminstall nodemon
npminstall jake
npminstall bloody-testserver

# warn about apps coming from app store
echo_space
echo_title "Don't forget to install via App Store"

if [ ! -d "/Applications/Twitter.app/" ]; then
  echo "- Twitter for Mac"
fi
if [ ! -d "/Applications/Xcode.app/" ]; then
  echo "- XCode"
fi
echo "- Network Link Conditioner"

# hack to make doctor not crying about `make`
# if type "/usr/local/bin/make" > /dev/null; then
#   brew unlink make > /dev/null
# fi

echo_space
echo_title "Doctor is checking..."
brew doctor

# come back `make`!
# brew link make --force > /dev/null

# done!
echo_space
echo_success "And... we're done!"

# resource!
source $HOME/.zshrc
