#! /usr/bin/env zsh
source $MY/core/helper

echo_title_install "symlinks"

# Screenshots
ln -sf ${SYNC_FOLDER}/Screenshots ~ 2> /dev/null

# App:espanso
ln -sf ${SYNC_FOLDER}/Appdata/espanso/espanso ~/Library/Preferences/espanso 2> /dev/null

# App:Rocket
ln -sf ${SYNC_FOLDER}/Appdata/Rocket/net.matthewpalmer.Rocket.plist ~/Library/Preferences/net.matthewpalmer.Rocket.plist 2> /dev/null
ln -sf ${SYNC_FOLDER}/Appdata/Rocket/Rocket ~/Library/Application\ Support/Rocket 2> /dev/null

# Resource!
source $HOME/.zshrc

echo_success "Symlinks are done!"
