#! /usr/bin/env zsh

source $MY/core/helper

# handle themes
if [ -d "$HOME/my/modules/themes" ]; then
  echo_space
  echo_title_update "themes"
  git --git-dir="$HOME/my/modules/themes/.git" --work-tree="$HOME/my/modules/themes/" pull
else
  echo_space
  echo_title_install "themes"
  git clone --recursive https://github.com/kud/themes.git "$HOME/my/modules/themes"
fi
