#! /usr/bin/env zsh

rm -rf $HOME/my

for dotfile in "${ZDOTDIR:-$HOME}"/my/dotfiles/.{aliases,editorconfig,gemrc,gitconfig,gitignore_global,prettierrc.js,vimrc,zshrc,zpreztorc}; do
  rm -rf "${ZDOTDIR:-$HOME}/${dotfile:t}" 2> /dev/null
done

rm -rf $HOME/.zprezto
