#! /usr/bin/env zsh

source $MY/core/helper

echo_title_update "\`my\`"
git --git-dir="$MY/.git" --work-tree="$MY/" pull &&

$MY/core/intro &&
$MY/core/default-folders &&
$MY/core/main &&
$MY/core/doctor

# done!
echo_space
echo_success "And... we're done!"

# resource!
source $HOME/.zshrc
