# Firefox Configuration

# Profile Configuration
profile:
  directory: "$HOME/Library/Application Support/Firefox/Profiles"
  default_folder_pattern: ".default-nightly"

# Global Preferences (converted to YAML hierarchy)
preferences:
  # ╔═════════════════════════════════════════════╗
  # ║                Global Preferences           ║
  # ╚═════════════════════════════════════════════╝

  browser:
    # Disable warning on about:config
    aboutConfig:
      showWarning: false

    # Turn off domain guessing
    fixup:
      alternate:
        enabled: false

    # Tab Management
    tabs:
      warnOnClose: false
      closeWindowWithLastTab: false
      firefox-view: false
      inTitlebar: 1

    # Search
    search:
      hiddenOneOffs: "Google,Bing,Amazon.co.uk,Chambers (UK),DuckDuckGo,eBay,Twitter,Wikipedia (en)"
      suggest:
        enabled: false

    # New Tab Page
    newtabpage:
      enabled: false
      activity-stream:
        showSearch: false
        showSponsored: false
        showSponsoredTopSites: false
        feeds:
          section:
            topstories: false
          topsites: false

    # Startup
    startup:
      homepage: "about:blank"

    # URL Bar
    urlbar:
      megabar: false
      suggest:
        quicksuggest:
          nonsponsored: false
          sponsored: false

    # Bookmarks
    toolbars:
      bookmarks:
        visibility: "never"
    bookmarks:
      showMobileBookmarks: false

    # Fullscreen
    fullscreen:
      autohide: true

    # Machine Learning
    ml:
      chat:
        enabled: true
        provider: "https://chatgpt.com"

  # Input Settings
  mousewheel:
    with_meta:
      action: 0

  keyword:
    enabled: false

  general:
    autoScroll: false

  # Find Settings
  findbar:
    modalHighlight: false

  # Network & Privacy
  network:
    IDN_show_punycode: true

  privacy:
    query_stripping:
      enabled: true

  # Extensions
  extensions:
    pocket:
      enabled: false
    formautofill:
      addresses:
        enabled: false # Disable address autofill
      creditCards:
        enabled: false # Disable credit card autofill

  # Media
  media:
    videocontrols:
      picture-in-picture:
        enable-when-switching-tabs:
          enabled: true

  # Sidebar
  sidebar:
    revamp: true
    verticalTabs: true

  # User Styles
  toolkit:
    legacyUserProfileCustomizations:
      stylesheets: true

  # Spellcheck
  layout:
    spellcheckDefault: 0

  signon:
    rememberSignons: false # Disable built-in password manager (use external)

  # ╔═════════════════════════════════════════════╗
  # ║                Sync Preferences             ║
  # ╚═════════════════════════════════════════════╝

  services:
    sync:
      prefs:
        sync:
          addons:
            ignoreUserEnabledChanges: true
      addons:
        ignoreUserEnabledChanges: true
      declinedEngines: "forms,history"

  # ╔═════════════════════════════════════════════╗
  # ║             Developer Tools Settings        ║
  # ╚═════════════════════════════════════════════╝

  devtools:
    chrome:
      enabled: true
    command-button-eyedropper:
      enabled: true
    command-button-paintflashing:
      enabled: true
    command-button-responsive:
      enabled: false
    command-button-scratchpad:
      enabled: true
    command-button-screenshot:
      enabled: true
    command-button-splitconsole:
      enabled: false
    debugger:
      remote-enabled: true
    dom:
      enabled: true
    editor:
      keymap: "sublime"
    onboarding:
      telemetry:
        logged: true
    performance:
      new-panel-enabled: true
    scratchpad:
      enabled: true
    screenshot:
      audio:
        enabled: false
    toolbox:
      host: "right"
    webconsole:
      timestampMessages: true
    webide:
      widget:
        enabled: true
    cache:
      disabled: true
    aboutdebugging:
      local-tab-debugging: true

# CSS Styling (userChrome.css content)
user_chrome_css: |
  /* No scroll on sidebar */
  #vertical-pinned-tabs-container {
    max-height: 100% !important;
  }

  /* Give background to any tab */
  #tabbrowser-arrowscrollbox {
    & .tab-background {
    .tabbrowser-tab:not(:hover) > .tab-stack > &:not([selected], [multiselected]) {
        background-color: color-mix(in srgb, currentColor 7%, transparent) !important;
      }
    }
  }

  /* Move container indicator */
  /*
  .tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
    #vertical-pinned-tabs-container &, #tabbrowser-tabs[orient="vertical"] & {
      margin: 4px -6px !important;
    }
  }
  */

  /* Hide close button on tab */
  /*
  .tab-close-button.close-icon {
    display: none !important;
  }
  */

  /* Set the right background for private window */
  #navigator-toolbox {
    :root[privatebrowsingmode] & {
      background-color: #281f4d !important;
    }
  }

  #sidebar-main {
    :root[privatebrowsingmode] & {
      background-color: #281f4d !important;
    }
  }

  /* Fix container line with Adaptive Tab Bar Colour addon */
  .tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
  #vertical-pinned-tabs-container &, #tabbrowser-tabs[orient="vertical"] & {
      margin-left: -2px !important;
      margin-right: -2px !important;
    }
  }

# Container Configuration
containers:
  version: 5
  lastUserContextId: 322
  identities:
    - icon: "fingerprint"
      color: "blue"
      public: true
      userContextId: 1
      name: "Personal"

    - icon: "briefcase"
      color: "red"
      public: true
      userContextId: 2
      name: "Work"

    - icon: "chill"
      color: "yellow"
      public: true
      userContextId: 318
      name: "Streaming"

    - icon: "fingerprint"
      color: "turquoise"
      public: true
      userContextId: 649
      name: "Personal at Work"

    - icon: "fence"
      color: "blue"
      public: true
      userContextId: 322
      name: "Facebook"

# Extension Settings
extension_settings:
  # Commands (keyboard shortcuts)
  # Extracted from extension-settings.json - actual configured shortcuts
  commands:
    # Easy Container Shortcuts Extension (firefox.container-shortcuts@strategery.io)
    easy_container_shortcuts:
      new_tab_current_container: "Command+MacCtrl+T"
      open_tab_container_1: "Command+MacCtrl+1"
      open_tab_container_2: "Command+MacCtrl+2"
      open_tab_container_3: "Command+MacCtrl+3"
      open_tab_container_4: "Command+MacCtrl+4"
      open_tab_container_5: "Command+MacCtrl+5"
      open_tab_container_6: "Command+MacCtrl+6"
      open_tab_container_7: "Command+MacCtrl+7"
      open_tab_container_8: "Command+MacCtrl+8"
      open_tab_container_9: "Command+MacCtrl+9"
      reopen_tab_default_container: "Command+MacCtrl+0"
      reopen_tab_container_1: "Command+MacCtrl+Shift+1"
      reopen_tab_container_2: "Command+MacCtrl+Shift+2"
      reopen_tab_container_3: "Command+MacCtrl+Shift+3"
      reopen_tab_container_4: "Command+MacCtrl+Shift+4"
      reopen_tab_container_5: "Command+MacCtrl+Shift+5"
      reopen_tab_container_6: "Command+MacCtrl+Shift+6"
      reopen_tab_container_7: "Command+MacCtrl+Shift+7"
      reopen_tab_container_8: "Command+MacCtrl+Shift+8"
      reopen_tab_container_9: "Command+MacCtrl+Shift+9"
      new_window_current_container: "Command+Alt+T"
      open_window_container_1: "Command+Alt+1"
      open_window_container_2: "Command+Alt+2"
      open_window_container_3: "Command+Alt+3"
      open_window_container_4: "Command+Alt+4"
      open_window_container_5: "Command+Alt+5"
      open_window_container_6: "Command+Alt+6"
      open_window_container_7: "Command+Alt+7"
      open_window_container_8: "Command+Alt+8"
      open_window_container_9: "Command+Alt+9"
      ecs_new_tab_container_1: "Alt+Shift+1"

    # Firefox Multi-Account Containers (@testpilot-containers)
    firefox_multi_account_containers:
      open_container_panel: "Command+MacCtrl+Period"

    # Email Address Plus (email-address-plus@kud.io)
    email_address_plus:
      copy_labeled_email: "Command+Shift+MacCtrl+Y"

    # Move Tab to Next Window ({3d4bf112-e248-40cb-89a5-00bbace3e56f})
    move_tab_to_next_window:
      move_tab: "Command+Shift+Alt+N"
      move_tab_alt: "Alt+Shift+N" # legacy shortcut

    # Temporary Containers ({c607c8df-14a7-4f28-894f-29e8722976af})
    temporary_containers:
      new_temporary_container_tab: "MacCtrl+Command+T"

    # Raindrop.io (jid0-adyhmvsP91nUO8pRv0Mn2VKeB84@jetpack)
    raindrop_io:
      bookmark_save_highlights: "Command+Shift+Alt+S"
      open_sidebar: "Command+MacCtrl+Period"
      save_page: "MacCtrl+S"
      execute_sidebar_action: "Command+Period"

    # Readwise Highlighter (team@readwise.io)
    readwise_highlighter:
      activate_toolbar_button: "Command+Alt+R"
      execute_browser_action: "MacCtrl+R"

    # KeePassXC Browser (keepassxc-browser@keepassxc.org)
    keepassxc_browser:
      fill_username_password: "MacCtrl+Shift+U"
      fill_password_only: "MacCtrl+Shift+I"
      fill_totp: "MacCtrl+Shift+O"
      show_password_generator: "MacCtrl+Shift+G"
      save_credentials: "MacCtrl+Shift+D"

  # Extension preferences (can be added here)
  prefs: {}

  # URL overrides (can be added here)
  url_overrides: {}

  # Default search settings (can be added here)
  default_search: {}
