#! /usr/bin/env zsh

source $MY/core/helper

echo_space
echo_title_update "macosx settings @ laptop"

###############################################################################
# General UI/UX                                                               #
###############################################################################

sudo scutil --set ComputerName "_kud.laptop"
sudo scutil --set HostName "_kud.laptop"
sudo scutil --set LocalHostName "kud-laptop"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "kud-laptop"
