# Claude Code Configuration - Work Profile
# Profile-specific MCP server settings for work usage

# MCP Servers
mcp:
  atlassian:
    transport: sse
    url: https://mcp.atlassian.com/v1/sse
  sentry:
    transport: sse
    url: https://mcp.sentry.dev/mcp
  figma-remote-mcp:
    transport: http
    url: https://mcp.figma.com/mcp
