# Claude Code Configuration - Work Profile
# Profile-specific MCP server settings for work usage

# MCP Servers
mcp:
  atlassian:
    transport: sse
    url: https://mcp.atlassian.com/v1/sse
  sentry:
    transport: stdio
    command: npx
    args:
      - mcp-remote
      - https://mcp.sentry.dev/mcp
  figma-remote:
    transport: http
    url: https://mcp.figma.com/mcp
  figma-local:
    transport: http
    url: http://127.0.0.1:3845/mcp
