# Codex CLI Configuration - Work Profile
# Extends the shared Codex config with additional MCP servers used at work.

mcp_servers:
  atlassian:
    url: https://mcp.atlassian.com/v1/sse
  sentry:
    command: npx
    args:
      - mcp-remote
      - https://mcp.sentry.dev/mcp
  figma-remote:
    url: https://mcp.figma.com/mcp
  figma-local:
    url: http://127.0.0.1:3845/mcp
