# OpenCode Configuration - Work Profile
# Profile-specific MCP server settings for work usage

# MCP Servers
mcp:
  atlassian:
    type: local
    enabled: false
    command:
      - npx
      - -y
      - mcp-remote
      - https://mcp.atlassian.com/v1/sse
  sentry:
    type: local
    enabled: false
    command:
      - npx
      - -y
      - mcp-remote
      - https://mcp.sentry.dev/mcp
  # figma-remote:
  #   type: local
  #   enabled: true
  #   command:
  #     - npx
  #     - -y
  #     - mcp-remote
  #     - https://mcp.figma.com/mcp
  # figma-local:
  #   type: remote
  #   enabled: true
  #   url: http://127.0.0.1:3845/mcp
