# OpenCode Configuration - Work Profile
# Profile-specific MCP server settings for work usage

# MCP Servers
mcp:
  atlassian:
    type: local
    enabled: false
    command:
      - npx
      - -y
      - mcp-remote
      - https://mcp.atlassian.com/v1/sse
  sentry:
    type: local
    enabled: false
    command:
      - npx
      - -y
      - mcp-remote
      - https://mcp.sentry.dev/mcp
  figma:
    type: local
    enabled: true
    command:
      - npx
      - -y
      - mcp-remote
      - https://mcp.figma.com/mcp
  # figma-local:
  #   type: remote
  #   enabled: true
  #   url: http://127.0.0.1:3845/mcp
  jenkins:
    type: local
    enabled: true
    command:
      - npx
      - --yes
      - "@kud/mcp-jenkins@latest"
    env:
      JENKINS_URL: ${MCP_JENKINS_URL}
      JENKINS_USER: ${MCP_JENKINS_USER}
      JENKINS_API_TOKEN: ${MCP_JENKINS_API_TOKEN}
  datadog:
    type: local
    enabled: true
    command:
      - npx
      - --yes
      - "@kud/mcp-datadog@latest"
    env:
      DD_API_KEY: ${MCP_DATADOG_API_KEY}
      DD_APP_KEY: ${MCP_DATADOG_APP_KEY}
      DD_SITE: ${MCP_DATADOG_SITE}
