#!/bin/zsh
autoload colors
if [[ "$terminfo[colors]" -gt 8 ]]; then
    colors
fi
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
    eval $COLOR='$fg_no_bold[${(L)COLOR}]'
    eval BOLD_$COLOR='$fg_bold[${(L)COLOR}]'
done
eval RESET='$reset_color'

export HOMEBREW_CASK_OPTS=--appdir=/Applications

function brewinstall() {
  brew install "${@}" 2> /dev/null
}

function caskinstall() {
  brew cask install "${@}" 2> /dev/null
}

printf "\n༼ ᕤ﻿◕◡◕ ༽ᕤ﻿ \`my\` ༼ ᕤ﻿◕◡◕ ༽ᕤ\n\n﻿"

if ! type "brew" > /dev/null; then
  echo "${GREEN}=> Installing homebrew...${RESET}"
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
fi

if ! type "/usr/local/bin/zsh" > /dev/null; then
  echo "${GREEN}=> Installing zsh...${RESET}"
  brewinstall zsh
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/zsh $USER
  sudo mv /etc/{zshenv,zprofile}
fi

if ! type "/usr/local/bin/bash" > /dev/null; then
  echo "${GREEN}=> Installing bash...${RESET}"
  brewinstall bash
  echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
fi

echo "${GREEN}=> Updating brew...${RESET}"
brew update && brew upgrade

# hack to make doctor not crying about make
if type "/usr/local/bin/make" > /dev/null; then
  brew unlink make > /dev/null
fi

echo "${GREEN}=> Doctor is checking...${RESET}"
brew doctor || exit 1

echo "${GREEN}=> Tap some brew repos...${RESET}"
if ! brew tap | grep cask > /dev/null; then
  brew tap phinze/homebrew-cask
fi
if ! brew tap | grep dupes > /dev/null; then
  brew tap homebrew/dupes
fi

echo "${GREEN}=> Installing brew packages...${RESET}"
brewinstall homebrew/dupes/make
brew link make --force > /dev/null

brewinstall dnsmasq
brewinstall ssh-copy-id
brewinstall htop-osx
brewinstall homebrew/dupes/rsync

brewinstall git
brewinstall wget
brewinstall curl
brewinstall pv
brewinstall md5sha1sum
brewinstall tree

brewinstall ruby
brewinstall python
brewinstall node

brewinstall brew-cask

echo "${GREEN}=> Installing apps...${RESET}"
caskinstall google-chrome-canary
caskinstall firefox-aurora
caskinstall dropbox
caskinstall vlc
caskinstall alfred
caskinstall iterm2
caskinstall lime-chat
caskinstall f-lux
caskinstall app-cleaner
caskinstall keepass-x-2
caskinstall spectacle
caskinstall grand-perspective
caskinstall imagealpha
caskinstall imageoptim
caskinstall mou
caskinstall steam
caskinstall spotify
caskinstall tinygrab
caskinstall sublime-text-3
if ! type "subl" > /dev/null; then
  ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
fi

if [ -d "$HOME/.zprezto" ]; then
  echo "${GREEN}=> Updating Prezto...${RESET}"
  git --git-dir="$HOME/.zprezto/.git" --work-tree="$HOME/.zprezto/" pull
else
  echo "${GREEN}=> Installing Prezto...${RESET}"
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
fi

if [ -d "$HOME/my/modules/themes" ]; then
  echo "${GREEN}=> Updating themes...${RESET}"
  git --git-dir="$HOME/my/modules/themes/.git" --work-tree="$HOME/my/modules/themes/" pull
else
  echo "${GREEN}=> Installing themes..."
  git clone --recursive https://github.com/putaindecode/themes.git "$HOME/my/modules/themes"
fi

echo "${GREEN}=> Updating Gems...${RESET}"
gem update --system && gem update
echo "${GREEN}=> Updating global node modules..."
npm update -g

echo "${GREEN}=> Don't forget to install via App Store${RESET}"
echo "- Twitter for Mac"
echo "- XCode"

echo "${BLUE}And... we're done!${RESET}"

exec $SHELL
