#!/bin/zsh
echo '⤿ Time to synchronise...'

# copy prezto files
~/my/scripts/sync_prezto

# symlink dotfiles
ln -si ~/my/dotfiles/.aliases ~/.aliases
ln -si ~/my/dotfiles/.gemrc ~/.gemrc
ln -si ~/my/dotfiles/.gitconfig ~/.gitconfig
ln -si ~/my/dotfiles/.gitignore_global ~/.gitignore_global
ln -si ~/my/dotfiles/.zpreztorc ~/.zpreztorc
ln -si ~/my/dotfiles/.zshrc ~/.zshrc
ln -si ~/my/dotfiles/.editorconfig ~/.editorconfig

# symlink themes
ln -si ~/my/modules/themes/kud/limechat/kud.css ~/Library/Application\ Support/LimeChat/Themes/kud.css
ln -si ~/my/modules/themes/kud/limechat/kud.yaml ~/Library/Application\ Support/LimeChat/Themes/kud.yaml

# local files
touch ~/.gitconfig_local
touch ~/.zshrc.local

# symlink appdata
ln -si ~/Dropbox/appdata/iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
ln -si ~/Dropbox/appdata/limechat/net.limechat.LimeChat.plist ~/Library/Preferences/net.limechat.LimeChat.plist
ln -si ~/Dropbox/appdata/sublimetext3/Packages ~/Library/Application\ Support/Sublime\ Text\ 3
ln -si ~/Dropbox/appdata/sublimetext3/Installed\ Packages ~/Library/Application\ Support/Sublime\ Text\ 3
